// Аутентификация
export const AUTH_LOADING = 'AUTH_LOADING';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const PROFILE_UPDATED = 'PROFILE_UPDATED';
export const PROFILE_UPDATE_FAIL = 'PROFILE_UPDATE_FAIL';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';

// Проекты
export const PROJECT_LOADING = 'PROJECT_LOADING';
export const GET_PROJECTS_SUCCESS = 'GET_PROJECTS_SUCCESS';
export const GET_PROJECTS_FAIL = 'GET_PROJECTS_FAIL';
export const GET_PROJECT_SUCCESS = 'GET_PROJECT_SUCCESS';
export const GET_PROJECT_FAIL = 'GET_PROJECT_FAIL';
export const CREATE_PROJECT_SUCCESS = 'CREATE_PROJECT_SUCCESS';
export const CREATE_PROJECT_FAIL = 'CREATE_PROJECT_FAIL';
export const UPDATE_PROJECT_SUCCESS = 'UPDATE_PROJECT_SUCCESS';
export const UPDATE_PROJECT_FAIL = 'UPDATE_PROJECT_FAIL';
export const DELETE_PROJECT_SUCCESS = 'DELETE_PROJECT_SUCCESS';
export const DELETE_PROJECT_FAIL = 'DELETE_PROJECT_FAIL';
export const CLEAR_PROJECT_ERRORS = 'CLEAR_PROJECT_ERRORS';

// Элементы канваса
export const CANVAS_LOADING = 'CANVAS_LOADING';
export const ADD_ELEMENT_SUCCESS = 'ADD_ELEMENT_SUCCESS';
export const ADD_ELEMENT_FAIL = 'ADD_ELEMENT_FAIL';
export const UPDATE_ELEMENT_SUCCESS = 'UPDATE_ELEMENT_SUCCESS';
export const UPDATE_ELEMENT_FAIL = 'UPDATE_ELEMENT_FAIL';
export const DELETE_ELEMENT_SUCCESS = 'DELETE_ELEMENT_SUCCESS';
export const DELETE_ELEMENT_FAIL = 'DELETE_ELEMENT_FAIL';

// Временная шкала
export const SET_TIMELINE_CURRENT_TIME = 'SET_TIMELINE_CURRENT_TIME';
export const SET_TIMELINE_PLAYING = 'SET_TIMELINE_PLAYING';
export const SET_TIMELINE_PLAYBACK_SPEED = 'SET_TIMELINE_PLAYBACK_SPEED';
export const SELECT_KEYFRAME = 'SELECT_KEYFRAME';
export const DESELECT_KEYFRAME = 'DESELECT_KEYFRAME';
export const SET_TIMELINE_DURATION = 'SET_TIMELINE_DURATION';
export const ADD_KEYFRAME = 'ADD_KEYFRAME';
export const UPDATE_KEYFRAME = 'UPDATE_KEYFRAME';
export const DELETE_KEYFRAME = 'DELETE_KEYFRAME';
export const UPDATE_TIMELINE = 'UPDATE_TIMELINE';
export const STOP_AT_END = 'STOP_AT_END';
export const RESET_TIMELINE = 'RESET_TIMELINE'; 